#!/bin/bash

if [[ "$1" == "-h" ]]; then
   echo "Start my Conky configuration"
   echo
   echo "USAGE: run         Start Conky"
else
    conky -dqc $HOME/.conky/3
    conky -dqc $HOME/.conky/2
    conky -dqc $HOME/.conky/1
fi
