(custom-set-variables
  ;; custom-set-variables was added by Custom.
  ;; If you edit it by hand, you could mess it up, so be careful.
  ;; Your init file should contain only one such instance.
  ;; If there is more than one, they won't work right.
 '(column-number-mode t)
 '(display-time-mode t)
 '(doc-view-continuous t)
 '(doc-view-resolution 192)
 '(eshell-directory-name "~/.emacs.d/eshell")
 '(gnus-inhibit-startup-message t)
 '(gnus-init-file "~/.emacs.d/gnus/startup.el")
 '(gnus-select-method (quote (nnrss "news")))
 '(gnus-startup-file "~/.emacs.d/gnus/newsrc")
 '(indicate-empty-lines t)
 '(inhibit-startup-screen t)
 '(ispell-dictionary "american")
 '(ispell-following-word t)
 '(ispell-highlight-face (quote flyspell-incorrect))
 '(ispell-personal-dictionary "~/.emacs.d/dict")
 '(ispell-program-name "/usr/bin/ispell")
 '(jabber-account-list (quote (("pavpanchekha@gmail.com" (:network-server . "talk.google.com") (:connection-type . ssl)))))
 '(jabber-avatar-cache-directory "/tmp/jabber-avatars")
 '(jabber-backlog-days 3.0)
 '(jabber-chat-buffer-show-avatar nil)
 '(jabber-chat-foreign-prompt-format "> ")
 '(jabber-chat-local-prompt-format "> ")
 '(jabber-chat-system-prompt-format "*** ")
 '(jabber-chat-time-format "%H:%M")
 '(jabber-default-show "")
 '(jabber-groupchat-prompt-format "%n> ")
 '(jabber-muc-private-foreign-prompt-format "%g/%n> ")
 '(jabber-roster-line-format "%c %-25n %u %-8s  %S")
 '(jabber-roster-show-title nil)
 '(jabber-show-offline-contacts nil)
 '(mail-source-crash-box "/tmp/pavpanchekha-emacs-mail-crash-box")
 '(mail-source-directory "/tmp/")
 '(mail-source-incoming-file-prefix "incoming-")
 '(menu-bar-mode t)
 '(newsticker-cache-filename "~/.emacs.d/newsticker/cache")
 '(newsticker-html-renderer (quote w3m-region))
 '(newsticker-url-list (quote (("Ars Technica, Open Ended" "http://feeds.arstechnica.com/arstechnica/open-source" nil nil nil) ("Motho ke motho ka botho" "http://kmandla.wordpress.com/feed/" nil nil nil) ("Planet GNOME" "http://planet.gnome.org/atom.xml" nil nil nil) ("Good Math, Bad Math" "http://scientopia.org/blogs/goodmath/feed/" nil nil nil) ("Planet Python" "http://planet.python.org/rss20.xml" nil nil nil) ("Existential Type" "http://existentialtype.wordpress.com/feed/" nil nil nil) ("Lambda the Ultimate" "http://lambda-the-ultimate.org/rss.xml" nil nil nil) ("Lingua Computa" "http://nonchalantlytyped.net/blog/feed/" nil nil nil) ("One Div Zero" "http://james-iry.blogspot.com/feeds/posts/default" nil nil nil) ("The Axis Of Eval" "http://www.blogger.com/feeds/5722310642266356003/posts/default" nil nil nil) ("Coding Horror" "http://feeds.feedburner.com/codinghorror/" nil nil nil) ("dive into mark" "http://feeds.feedburner.com/diveintomark/all" nil nil nil) ("Paul Graham: Essays" "http://www.aaronsw.com/2002/feeds/pgessays.rss" nil nil nil) ("Abstruse Goose" "http://abstrusegoose.com/feed/atom" nil nil nil) ("XKCD Blog" "http://blag.xkcd.com/feed/" nil nil nil) ("XKCD Comic" "http://www.xkcd.com/rss.xml" nil nil nil))))
 '(newsticker-url-list-defaults nil)
 '(nnmail-message-id-cache-file "/tmp/pavpanchekha-nnmail-cache")
 '(preview-scale-function 1.1)
 '(rmail-default-body-file "~/mail/out")
 '(rmail-default-file "~/mail")
 '(rmail-display-summary t)
 '(rmail-displayed-headers "^To:\\|From:\\|Date:\\|Subject:")
 '(rmail-file-name "~/mail/inbox")
 '(rmail-inbox-list (quote ("~/mail/inbox.spool" "~/mail/reuse.mit.spool" "~/mail/remind-fans.spool" "~/mail/lisp-hug.spool")) t)
 '(rmail-mime-show-images nil)
 '(rmail-preserve-inbox t)
 '(rmail-primary-inbox-list (quote ("/var/spool/mail/pavpanchekha" "~/mail/reuse.mit" "~/mail/remind-fans" "lisp-hug")))
 '(rmail-redisplay-summary t)
 '(rmail-secondary-file-directory "~/mail")
 '(rmail-secondary-file-regexp "~/mail/*")
 '(rmail-summary-scroll-between-messages nil)
 '(scroll-bar-mode nil)
 '(size-indication-mode t)
 '(slime-backend "~/.emacs.d/slime/loader.lsp")
 '(tool-bar-mode nil)
 '(w3m-coding-system (quote utf-8))
 '(w3m-default-coding-system (quote utf-8))
 '(w3m-default-display-inline-images t)
 '(w3m-default-save-directory "/tmp")
 '(w3m-favicon-size (quote (16 . 16)))
 '(w3m-file-coding-system (quote utf-8))
 '(w3m-file-name-coding-system (quote utf-8))
 '(w3m-home-page "about:blank")
 '(w3m-icon-directory "/tmp")
 '(w3m-init-file "~/.emacs.d/w3m.el")
 '(w3m-key-binding nil)
 '(w3m-terminal-coding-system (quote utf-8))
 '(w3m-use-favicon t))
(custom-set-faces
  ;; custom-set-faces was added by Custom.
  ;; If you edit it by hand, you could mess it up, so be careful.
  ;; Your init file should contain only one such instance.
  ;; If there is more than one, they won't work right.
 '(jabber-chat-prompt-foreign ((t (:foreground "red"))))
 '(jabber-chat-prompt-local ((t (:foreground "blue"))))
 '(jabber-chat-prompt-system ((t (:foreground "dark green" :weight bold))))
 '(jabber-roster-user-away ((t (:foreground "orange"))))
 '(jabber-roster-user-chatty ((t (:foreground "green"))))
 '(jabber-roster-user-online ((t (:foreground "dark green")))))
